export enum UserRole {
  APPLICANT = 'APPLICANT',
  STUDENT = 'STUDENT',
  PROFESSOR = 'PROFESSOR',
  ALUMNI = 'ALUMNI',
  APPLICANT_ADMIN = 'APPLICANT_ADMIN',
  STUDENT_ADMIN = 'STUDENT_ADMIN',
  ALUMNI_ADMIN = 'ALUMNI_ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}
